apiVersion: v1
kind: Service
metadata:
  labels:
    app: thinknyxdemoagain
  name: thinknyxdemosvcagain
spec:
  ports:
  - name: testsvcagain
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: thinknyxdemoagain
  type: NodePort
